// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/applications" | "/admin/applications/[id]" | "/admin/booking-links" | "/admin/calendar" | "/admin/dashboard" | "/admin/login" | "/booking/[token]" | "/doctor" | "/legal/consent" | "/legal/offer" | "/legal/privacy" | "/not-suitable" | "/payment/success" | "/portal/materials/[token]" | "/portal/messages" | "/questionnaire" | "/services" | "/services/medical-route" | "/services/personal-support" | "/services/recovery-4-weeks" | "/services/second-opinion"
type AppRouteHandlerRoutes = "/api/admin/applications/[id]/activate" | "/api/admin/applications/[id]/complete" | "/api/admin/applications/[id]/create-offer" | "/api/admin/applications/[id]/messages/reply" | "/api/admin/applications/[id]/reject" | "/api/admin/applications/[id]/request-imaging-access" | "/api/admin/applications/[id]/request-upload" | "/api/admin/applications/[id]/sensitive-access" | "/api/admin/calendar/slots" | "/api/admin/calendar/slots/[id]" | "/api/admin/login" | "/api/admin/logout" | "/api/booking/[token]/checkout" | "/api/booking/[token]/hold-slot" | "/api/portal/materials/[token]/complete" | "/api/portal/materials/[token]/links" | "/api/portal/materials/[token]/presign" | "/api/portal/materials/[token]/submit" | "/api/portal/thread/messages" | "/api/questionnaire" | "/api/uploads/complete" | "/api/uploads/presign" | "/api/webhooks/payments" | "/portal/access/[token]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/applications": {}
  "/admin/applications/[id]": { "id": string; }
  "/admin/booking-links": {}
  "/admin/calendar": {}
  "/admin/dashboard": {}
  "/admin/login": {}
  "/api/admin/applications/[id]/activate": { "id": string; }
  "/api/admin/applications/[id]/complete": { "id": string; }
  "/api/admin/applications/[id]/create-offer": { "id": string; }
  "/api/admin/applications/[id]/messages/reply": { "id": string; }
  "/api/admin/applications/[id]/reject": { "id": string; }
  "/api/admin/applications/[id]/request-imaging-access": { "id": string; }
  "/api/admin/applications/[id]/request-upload": { "id": string; }
  "/api/admin/applications/[id]/sensitive-access": { "id": string; }
  "/api/admin/calendar/slots": {}
  "/api/admin/calendar/slots/[id]": { "id": string; }
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/booking/[token]/checkout": { "token": string; }
  "/api/booking/[token]/hold-slot": { "token": string; }
  "/api/portal/materials/[token]/complete": { "token": string; }
  "/api/portal/materials/[token]/links": { "token": string; }
  "/api/portal/materials/[token]/presign": { "token": string; }
  "/api/portal/materials/[token]/submit": { "token": string; }
  "/api/portal/thread/messages": {}
  "/api/questionnaire": {}
  "/api/uploads/complete": {}
  "/api/uploads/presign": {}
  "/api/webhooks/payments": {}
  "/booking/[token]": { "token": string; }
  "/doctor": {}
  "/legal/consent": {}
  "/legal/offer": {}
  "/legal/privacy": {}
  "/not-suitable": {}
  "/payment/success": {}
  "/portal/access/[token]": { "token": string; }
  "/portal/materials/[token]": { "token": string; }
  "/portal/messages": {}
  "/questionnaire": {}
  "/services": {}
  "/services/medical-route": {}
  "/services/personal-support": {}
  "/services/recovery-4-weeks": {}
  "/services/second-opinion": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
