// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(public)/booking/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/booking/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/doctor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/doctor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/legal/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/consent">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/legal/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/legal/offer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/offer">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/legal/offer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/legal/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/legal/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/not-suitable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/not-suitable">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/not-suitable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/payment/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/success">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/payment/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/questionnaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questionnaire">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/questionnaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/medical-route/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/medical-route">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/medical-route/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/personal-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/personal-support">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/personal-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/recovery-4-weeks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/recovery-4-weeks">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/recovery-4-weeks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/second-opinion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/second-opinion">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/second-opinion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/applications">> = Specific
  const handler = {} as typeof import("../../src/app/admin/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/booking-links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/booking-links">> = Specific
  const handler = {} as typeof import("../../src/app/admin/booking-links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/admin/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/materials/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/materials/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/materials/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/messages">> = Specific
  const handler = {} as typeof import("../../src/app/portal/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/create-offer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/create-offer">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/create-offer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/messages/reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/messages/reply">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/messages/reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/request-imaging-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/request-imaging-access">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/request-imaging-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/request-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/request-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/request-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/applications/[id]/sensitive-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications/[id]/sensitive-access">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/applications/[id]/sensitive-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/calendar/slots/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar/slots/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/calendar/slots/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/calendar/slots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar/slots">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/calendar/slots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/booking/[token]/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/[token]/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/booking/[token]/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/booking/[token]/hold-slot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking/[token]/hold-slot">> = Specific
  const handler = {} as typeof import("../../src/app/api/booking/[token]/hold-slot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/materials/[token]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/materials/[token]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/materials/[token]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/materials/[token]/links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/materials/[token]/links">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/materials/[token]/links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/materials/[token]/presign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/materials/[token]/presign">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/materials/[token]/presign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/materials/[token]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/materials/[token]/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/materials/[token]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/thread/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/thread/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/thread/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/questionnaire/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questionnaire">> = Specific
  const handler = {} as typeof import("../../src/app/api/questionnaire/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/presign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/presign">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/presign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/access/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/portal/access/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/access/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
